### ISSUE TITLE
Responsive Project Images & Card

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet/planet-webapp#83]
- [x] Do not repeat images on responsive. instead use cover center.
<img width="683" alt="Screen Shot 2020-08-20 at 12 04 14 PM" src="https://user-images.githubusercontent.com/5401575/90756997-54686900-e2dd-11ea-9c61-0528ab986342.png">

- [x] On Ipad size screens, cards can be stacked  on two columns on flexbox/grid

<img width="835" alt="Screen Shot 2020-08-20 at 12 05 47 PM" src="https://user-images.githubusercontent.com/5401575/90757179-9b565e80-e2dd-11ea-8aa4-024c5fd497e6.png">

**Comment by harshvitra** [comment]
This has been solved with a better approach of having max width to the column for tablet and higher sizes

**Comment by sagararyal** [comment]
@harshvitra this is still not solved.

No scroll is possible in this case.
<img width="710" alt="Screen Shot 2020-09-02 at 6 36 28 PM" src="https://user-images.githubusercontent.com/5401575/92011333-37a34b00-ed4b-11ea-93b6-b458b75df1e8.png">

**Comment by sagararyal** [comment]
Zoom 2 needs to be considered in this as well
<img width="701" alt="Screen Shot 2020-09-02 at 6 37 21 PM" src="https://user-images.githubusercontent.com/5401575/92011438-59043700-ed4b-11ea-90d3-f8cbd44b3ce3.png">
